config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'home', to: 'home#index'
  get 'cookie-policy', to: 'cookie_policy#index'

  resources :faq, only: [:index]
  resources :feedbacks, only: [:create]
end

app/models/ahoy/event.rb
# == Schema Information
#
# Table name: ahoy_events
#
#  id         :integer          not null, primary key
#  visit_id   :integer
#  user_id    :integer
#  name       :string
#  properties :text
#  time       :datetime
#
class Ahoy::Event < ApplicationRecord
  include Ahoy::QueryMethods

  self.table_name = "ahoy_events"

  belongs_to :visit
  belongs_to :user, optional: true

  serialize :properties, JSON
end

app/models/ahoy/visit.rb
# == Schema Information
#
# Table name: ahoy_visits
#
#  id               :integer          not null, primary key
#  visit_token      :string
#  visitor_token    :string
#  user_id          :integer
#  ip               :string
#  user_agent       :text
#  referrer         :text
#  referring_domain :string
#  landing_page     :text
#  browser          :string
#  os               :string
#  device_type      :string
#  country          :string
#  region           :string
#  city             :string
#  latitude         :float
#  longitude        :float
#  utm_source       :string
#  utm_medium       :string
#  utm_term         :string
#  utm_content      :string
#  utm_campaign     :string
#  app_version      :string
#  os_version       :string
#  platform         :string
#  started_at       :datetime
#
class Ahoy::Visit < ApplicationRecord
  self.table_name = "ahoy_visits"

  has_many :events, class_name: "Ahoy::Event"
  belongs_to :user, optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dashboard.rb
class Dashboard
  def self.url
    return ENV["DASHBOARD_URL_EN"] if I18n.locale.to_s == "en"

    ENV["DASHBOARD_URL_KM"]
  end
end

app/models/feedback.rb
# == Schema Information
#
# Table name: feedbacks
#
#  id         :integer          not null, primary key
#  email      :string
#  message    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Feedback < ApplicationRecord
  # Validation
  validates :email, format: { with: /\A[^@\s]+@[^@\s]+\z/ }, allow_blank: true
  validates :message, presence: true

  # Callback
  after_create :notify_supporter

  private
    def notify_supporter
      FeedbackMailer.notify(self).deliver_now
    end
end

app/models/setting.rb
class Setting
  def self.analytics_valid?
    GoogleAnalytics.valid_tracker? && Rails.env.production?
  end

  def self.visit_duration
    (ENV.fetch("VISIT_DURATION_MINUTE") { 30 }).to_i.minutes
  end
end

app/models/social_meta_tag.rb
# frozen_string_literal: true

class SocialMetaTag
  def self.to_meta_tags
    {
      og: {
        title:  I18n.t("meta_tags.title"),
        site_name: I18n.t("meta_tags.site"),
        type: "website",
        description: I18n.t("meta_tags.description"),
        image: helper.image_url("csc_logo.png")
      },
      twitter: {
        title: I18n.t("meta_tags.title"),
        creator: I18n.t("meta_tags.site"),
        site: I18n.t("meta_tags.twitter.site"),
        card: "summary",
        description: I18n.t("meta_tags.description"),
        image: helper.image_url("csc_logo.png")
      },
    }
  end

  private
    def self.helper
      ActionController::Base.helpers
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  before_action :set_gon_variable

  private
    def set_locale
      session[:locale] = params[:locale] if params[:locale].present?

      I18n.locale = session[:locale] || I18n.default_locale
    end

    # Set variable to use in js
    def set_gon_variable
      gon.push({
        cookiePolicyPath: cookie_policy_path,
      })
    end

    def visitor_count
      @visitor_count ||= Ahoy::Visit.count
    end
    helper_method :visitor_count

    def feedback
      @feedback ||= Feedback.new
    end
    helper_method :feedback
end

app/controllers/cookie_policy_controller.rb
class CookiePolicyController < ApplicationController
  layout "minimal"

  def index; end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def create
    @feedback = Feedback.new(feedback_params)

    if verify_recaptcha(model: @feedback) && @feedback.save
      @feedback = Feedback.new

      flash.now[:notice] = I18n.t("feedback.send_successfully")
    else
      flash.now[:alert] = @feedback.errors.full_messages.join(', ')
    end
  end

  private
    def feedback_params
      params.require(:feedback).permit(:email, :message)
    end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def css_class_name
    "#{controller_path.parameterize}-#{action_name}"
  end

  def human_size(num, units={ thousand: 'K', million: 'M' }, format: '%n%u')
    number_to_human num, units: units, format: format
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/abouts/show.html.haml
.d-flex.my-4.mx-auto.introduction.justify-content-between
  = link_to t('shared.back'), root_path, class: 'invisible'
  = link_to t('shared.sign_in'), ENV['SIGN_URL'], target: '_blank'

.row
  .col-md-12
    .text-center
      = image_tag 'csc_logo.png', size: '120x120', alt: "CSC logo"

.d-flex.justify-content-center.mt-4.mb-3.mx-auto.introduction
  %h5.font-weight-bolder{ style: "line-height: 1.5em"}
    កម្មវិធីប័ណ្ណដាក់ពិន្ទុឌីជីថល ត្រូវបានបង្កើតឡើងដោយមានការគាំទ្រមូលនិធិពីសហភាពអឺរ៉ុប អនុវត្តដោយអង្គការឃែរកម្ពុជា វិទ្យាស្ថានគោលនយោបាយនិងតស៊ូមតិ និងអង្គការ InSTEDD នៃគម្រោង “គាំទ្រការចូលរួមរបស់ប្រជាពលរដ្ឋប្រកបដោយអត្ថន័យតាមរយៈការប្រើប្រាស់បច្ចេកវិទ្យាឌីជីថល ដើម្បីធ្វើឱ្យសើរឡើងនូវគណនេយ្យភាពសង្គម (Ref: ISAF-II)”។

    ប្រជាពលរដ្ឋ អង្គការដៃគូ និងមន្រ្តីរដ្ឋាភិបាលប្រើប្រាស់កម្មវិធីនេះដើម្បីលើកកម្ពស់ការចូលរួម និងកិច្ចជជែកពិភាក្សារបស់ពួកគេ ក្នុងការធ្វើឱ្យប្រសើរឡើងនូវសេវាសាធារណៈ។

.d-flex.justify-content-center.mb-4.mx-auto.introduction.text-center
  The digitised scorecard app development is funded by the EU, implemented by CARE, API and InSTEDD iLab SEA under the project “supports civic engagement and improves social accountability by leveraging digital technologies (Re: ISAF-II)”.

  The community members, local NGO partners and governmental officials use the app to enhance their participation and dialogue with regards to public services improvement.

.d-flex.justify-content-between.my-5.mx-auto.introduction
  .learn-more
    %h5.font-weight-bold.text-center
      %span= "អាចស្វែងយល់បន្ថែមនៅលើ FAQs ដោយគ្រាន់តែចុច"
      %span= link_to 'នៅទីនេះ', faq_path
      %span= ". សម្រាប់អ្នកមិនមានគណនីហើយដែលចង់ស្វែងយល់បន្ថែមសូមទាក់ទងមកយើងតាមរយៈ support@digital-csc.org"
    %h6.text-center
      %span= "To learn more from our FAQs, click "
      %span= link_to 'here', faq_path
      %span= ". if you don't have an account and want to learn more please reach out to use via: support@digital-csc.org"

.introduction.mx-auto
  .stackholders.d-flex.justify-content-between.stackholders-lg
    .funded-by.text-center.flex-shrink-0
      %p.font-weight-bold.text-center.text-funded
        គាំទ្រមូលនិធិដោយ / Funded by

      = link_to 'https://eeas.europa.eu/delegations/cambodia_en', target: '_blank' do
        = image_tag 'eu.png', class: 'img-funded', alt: 'EU Cambodia'

    .implemented-by
      %p.font-weight-bold.text-center.text-implemented
        អនុវត្តដោយ / Implemented by
      .d-flex.align-items-center.justify-content-center.flex-wrap.img-implemented-wrapper
        = link_to 'https://www.care-cambodia.org/', target: '_blank' do
          = image_tag 'care_logo.png', class: 'img-implemented', alt: 'Care'

        = link_to 'https://apiinstitute.org/', target: '_blank' do
          = image_tag 'api.png', class: 'img-implemented', alt: 'API'

        = link_to 'http://ilabsoutheastasia.org', target: '_blank' do
          = image_tag 'instedd-ilabsea.png', class: 'img-implemented', alt: 'InSTEDD iLabSEA'


%div{ style: "height: 200px"}

app/views/cookie_policy/index.haml
.container
  .row
    .col-xs-12
      %h1.my-5.text-center Cookies Policy
      %p.mb-3 Last updated: June 09, 2021

      %p
        This Cookies Policy explains what Cookies are and how We use them. You should read this policy so You can understand what type of cookies We use, or the information We collect using Cookies and how that information is used.
      %p Cookies do not typically contain any information that personally identifies a user, but personal information that we store about You may be linked to the information stored in and obtained from Cookies. For further information on how We use, store and keep your personal data secure, see our Privacy Policy.
      %p We do not store sensitive personal information, such as mailing addresses, account passwords, etc. in the Cookies We use.
      %h3.mt-5 Interpretation and Definitions
      %h4.section-header Interpretation
      %p The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      %h4.section-header Definitions
      %p For the purposes of this Cookies Policy:
      %ul
        %li
          %strong Company
          (referred to as either "the Company", "We", "Us" or "Our" in this Cookies Policy) refers to
          = "#{ENV['ORG_NAME']}, "
          = "#{ENV['ORG_ADDR']}"
        %li
          %strong Cookies
          means small files that are placed on Your computer, mobile device or any other device by a website, containing details of your browsing history on that website among its many uses.
        %li
          %strong Website
          = "refers to #{ENV['SITE_NAME']}, accessible from"
          = link_to ENV['SITE_NAME'], ENV['BASE_URL']
        %li
          %strong You
          means the individual accessing or using the Website, or a company, or any legal entity on behalf of which such individual is accessing or using the Website, as applicable.
      %h1 The use of the Cookies
      %h4.section-header Type of Cookies We Use
      %p Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser.
      %p We use both session and persistent Cookies for the purposes set out below:
      %ul
        %li
          %p
            %strong Necessary / Essential Cookies
          %p Type: Session Cookies
          %p Administered by: Us
          %p Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
        %li
          %p
            %strong Functionality Cookies
          %p Type: Persistent Cookies
          %p Administered by: Us
          %p Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
      %h4.section-header Your Choices Regarding Cookies
      %p If You prefer to avoid the use of Cookies on the Website, first You must disable the use of Cookies in your browser and then delete the Cookies saved in your browser associated with this website. You may use this option for preventing the use of Cookies at any time.
      %p If You do not accept Our Cookies, You may experience some inconvenience in your use of the Website and some features may not function properly.
      %p If You'd like to delete Cookies or instruct your web browser to delete or refuse Cookies, please visit the help pages of your web browser.
      %ul
        %li
          %p
            For the Chrome web browser, please visit this page from Google:
            %a{:href => "https://support.google.com/accounts/answer/32050", :rel => "external nofollow noopener", :target => "_blank"} https://support.google.com/accounts/answer/32050
        %li
          %p
            For the Internet Explorer web browser, please visit this page from Microsoft:
            %a{:href => "http://support.microsoft.com/kb/278835", :rel => "external nofollow noopener", :target => "_blank"} http://support.microsoft.com/kb/278835
        %li
          %p
            For the Firefox web browser, please visit this page from Mozilla:
            %a{:href => "https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored", :rel => "external nofollow noopener", :target => "_blank"} https://support.mozilla.org/en-US/kb/delete-cookies-remove-info-websites-stored
        %li
          %p
            For the Safari web browser, please visit this page from Apple:
            %a{:href => "https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac", :rel => "external nofollow noopener", :target => "_blank"} https://support.apple.com/guide/safari/manage-cookies-and-website-data-sfri11471/mac
      %p For any other web browser, please visit your web browser's official web pages.
      %h4.section-header More Information about Cookies
      %p
        You can learn more about cookies:
        = succeed "." do
          %a{:href => "http://www.aboutcookies.org/", :target => "_blank"} What Are Cookies?
      %h4.section-header Contact Us
      %p If you have any questions about this Cookies Policy, You can contact us:
      %ul.mb-5
        %li
          By phone number:
          = link_to ENV['CONTACT_PHONE_NUMBER'], "tel:#{ENV['CONTACT_PHONE_NUMBER']}"
        %li
          By email:
          = mail_to ENV['CONTACT_EMAIL']

app/views/faq/index.html.haml
#faq-wraper.d-flex.justify-content-center.mx-auto
  .content
    %h5.my-4.text-center.title= t('faq')

    #faq.accordion.accordion-flush
      = render 'faq/index/question_1'
      = render 'faq/index/question_2'
      = render 'faq/index/question_3'
      = render 'faq/index/question_4'
      = render 'faq/index/question_5'
      = render 'faq/index/question_6'
      = render 'faq/index/question_7'

app/views/faq/index/_question.haml
.accordion-header
  .heading.accordion-button.collapsed{"aria-controls" => "collapse#{target}", "aria-expanded" => "false", "data-bs-target" => "#collapse#{target}", "data-bs-toggle" => "collapse", id: "heading#{target}" }
    .question= question.html_safe

app/views/faq/index/_question_1.haml
.accordion-item.mb-2.shadow.border
  = render 'faq/index/question', target: 'One', question: t('question.can_my_project_use_digital_scorecard')

  #collapseOne.accordion-collapse.collapse{"aria-labelledby" => "headingOne", "data-bs-parent" => "#faq"}
    .faq-body.accordion-body
      = t('answer.q1.yes_digital_scorecard_is_free').html_safe

app/views/faq/index/_question_2.haml
.accordion-item.mb-2.shadow.border
  = render 'faq/index/question', target: 'Two', question: t('question.why_should_i_use_digital_scorecard')

  #collapseTwo.accordion-collapse.collapse{"aria-labelledby" => "headingTwo", "data-bs-parent" => "#faq"}
    .faq-body
      = t('answer.q2.digital_scorecard_was_designed').html_safe

      %ul
        %li= t('answer.q2.it_provide_flexibility').html_safe
        %li= t('answer.q2.it_support_khmer_language').html_safe
        %li= t('answer.q2.it_come_with_dashboard').html_safe

      = link_to t('answer.q2.see_here_videos'), "https://www.youtube.com/playlist?list=PLOpKUpKkRrQuWggZRMSIjgAjixiZhXT-j", target: '_blank'

      %span= t('answer.q2.about_digital_scorecard').html_safe

app/views/faq/index/_question_3.haml
.accordion-item.border.mb-2.shadow
  = render 'faq/index/question', target: 'Three', question: t('question.why_should_i_not_reinvent_the_wheel')

  #collapseThree.accordion-collapse.collapse{"aria-labelledby" => "headingThree", "data-bs-parent" => "#faq"}
    .faq-body
      %ol
        %li= t('answer.q3.save_resource').html_safe
        %li= t('answer.q3.has_an_existing_community').html_safe
        %li= t('answer.q3.if_feel_not_match_purpose_let_consult').html_safe

app/views/faq/index/_question_4.haml
.accordion-item.border.mb-2.shadow
  = render 'faq/index/question', target: 'Four', question: t('question.how_to_set_up_digital_scorecard')

  #collapseFour.accordion-collapse.collapse{"aria-labelledby" => "headingFour", "data-bs-parent" => "#faq"}
    .faq-body
      = t('answer.q4.digital_scorecard_has_two_component').html_safe
      %ol
        %li
          = t('answer.q4.has_mobile_app').html_safe
          = link_to t('answer.q4.link_to_download').html_safe, "https://play.google.com/store/apps/details?id=org.instedd.ilabsea.community_scorecard&hl=km&gl=US", target: "_blank"
          = t('answer.q4.the_application').html_safe

        %li
          = t('answer.q4.install_backend_on_your_server').html_safe

          %ol.list-style-lower-alpha
            %li= link_to t('answer.q4.link_to_source_code'), "https://github.com/ilabsea/scorecard-web", target: "_blank"

        %li= t('answer.q4.configure_on_mobile_app').html_safe

app/views/faq/index/_question_5.haml
.accordion-item.border.mb-2.shadow
  = render 'faq/index/question', target: 'Five', question: t('question.is_there_central_digital_scorecard')

  #collapseFive.accordion-collapse.collapse{"aria-labelledby" => "headingFive", "data-bs-parent" => "#faq"}
    .faq-body
      = t('answer.q5.yes_there_is_central_digital_scorecard').html_safe
      .my-4
        = image_tag 'how-score-card-works.png', alt: 'How scorecard works', class: 'img-fluid'

app/views/faq/index/_question_6.haml
.accordion-item.border.mb-2.shadow
  = render 'faq/index/question', target: 'Six', question: t('question.where_can_i_get_support')

  #collapseSix.accordion-collapse.collapse{"aria-labelledby" => "headingSix", "data-bs-parent" => "#faq"}
    .faq-body
      %ul
        %li= t('answer.q6.please_contact_care_and_api').html_safe
        %li= t('answer.q6.please_contact_instedd').html_safe

app/views/faq/index/_question_7.haml
.accordion-item.border.mb-2.shadow
  = render 'faq/index/question', target: 'Seven', question: t('question.what_about_data_ownership')

  #collapseSeven.accordion-collapse.collapse{"aria-labelledby" => "headingSeven", "data-bs-parent" => "#faq"}
    .faq-body
      = t('answer.q7.the_data_owned_by_your_server').html_safe

app/views/feedbacks/_flash_message.html.haml
- if flash[:alert].present?
  .alert.alert-danger.alert-dismissible.fade.show{:role => "alert"}
    = flash[:alert]
    %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}

- if flash[:notice].present?
  .alert.alert-success.alert-dismissible.fade.show{:role => "alert"}
    = flash[:notice]
    %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}

app/views/feedbacks/_form.html.haml
- device_type ||= "desktop"

= render "feedbacks/flash_message"
/ Form
= simple_form_for feedback, remote: true do |f|
  = f.input :email, label: t('feedback.your_email')
  = f.input :message, label: t('feedback.your_comment')
  = recaptcha_tags

  %input{name: 'device_type', value: device_type, type: :hidden}

  .mt-4
    = f.submit t('shared.submit'), class: 'btn btn-primary'

app/views/feedbacks/create.js.erb
<% if params[:device_type] == "desktop" %>
  $('[data-name="popover-content"]').html('<%= j render("feedbacks/form", device_type: params[:device_type]) %>');
<% else %>
  $('.bottom-sheet-boday').html('<%= j render("feedbacks/form", device_type: params[:device_type]) %>');
  $('.body').animate({scrollTop: 0});
<% end %>

setTimeout(function() {
  $(".btn-close").click();
}, 5000)

app/views/home/_background.haml
.bg
  = image_tag 'bg.svg', style: 'width: 100%'

app/views/home/_footer.haml
.footer-wrapper
  .text-center
    %span.reach-us
      = t('footer.contact_us_via')
    %span.email
      - email = 'support@digital-csc.org'
      = link_to email, "mailto:#{email}", class: 'email'

  .text-center.copyright
    = t('footer.copyright').html_safe

app/views/home/_introduction.haml
.introduction.intro-layout.d-flex
  .d-flex.flex-column.mr-5
    %h5.title= t('introduction.the_digital_scorecard_app')
    .description
      = t('introduction.digital_scorecard_introduction').html_safe

    .d-flex.justify-content-center.download-wrapper
      .d-flex.flex-column.align-items-center
        .download-title.flex-grow-1= t('introduction.download_available')

        %a.play-store{href: 'https://play.google.com/store/apps/details?id=org.instedd.ilabsea.community_scorecard', target: '_blank'}
          = image_tag 'play_store.png'

      %div.qr-code-wrapper.ml-4
        = image_tag 'qr_code.png'

  .d-flex
    %div.divices-wrapper
      = image_tag 'devices.png'

app/views/home/_social_share.haml
%span.share-icon
  = t("social_share_button.share_on")

= social_share_button_tag t("meta_tags.site"), url: root_url, image: image_url("csc_logo.png"), "data-type": "photo"

.visitor-counter
  %span.badge.bg-info.rounded-pill
    %i.fa.fa-eye
    = "#{human_size(@visitor_count)}"

app/views/home/_stakeholder.haml
.stakeholder-wrapper.my-3.mx-auto
  .content.mx-auto.stakeholders
    .d-flex.justify-content-center
      .funded-by.text-center.me-4
        .funded-by-title.mb-2
          = t('stakeholder.funded_by')

        = link_to 'https://eeas.europa.eu/delegations/cambodia_en', target: '_blank' do
          = image_tag 'eu.png', class: 'img-funded', alt: 'EU Cambodia'

      .implemented-by.mx-3.d-flex.flex-column
        .implemented-by-title.mb-2.text-center
          = t('stakeholder.implemented_by')

        .d-flex.align-items-center.flex-grow-1
          = link_to 'https://www.care-cambodia.org/', target: '_blank' do
            = image_tag 'care_logo.png', class: 'img-implemented care', alt: 'Care'

          = link_to 'https://apiinstitute.org/', target: '_blank' do
            = image_tag 'api.png', class: 'img-implemented api', alt: 'API'

          = link_to 'http://ilabsoutheastasia.org', target: '_blank' do
            = image_tag 'instedd-ilabsea.png', class: 'img-implemented instedd', alt: 'InSTEDD iLabSEA'

app/views/home/_top_header.haml
.d-flex.justify-content-center.top-bar
  .content.d-flex.flex-grow-1.align-items-center
    .flex-grow-1
      = link_to root_url do
        = image_tag 'logo.png', class: 'logo'

    .faq-link
      = link_to "FAQ", faq_index_path, class: 'btn text-white'

    / Switch language
    #switch-language.btn-group
      %a#messagesDropdown.nav-link.dropdown-toggle.pe-0{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :type => "button", href: '#'}
        - language = { en: "english.png", km: "khmer.png" }
        = image_tag language[I18n.locale], alt: "locale", size: "24x24"
        %span.ms-1= t("language.#{I18n.locale}")
        %i.fas.fa-angle-down.fa-fw

      %ul.dropdown-menu.dropdown-menu-end
        %li
          = link_to url_for(request.query_parameters.merge(locale: 'km')), class: 'switch-language dropdown-item d-flex align-items-center' do
            .dropdown-list-image.me-3
              = image_tag "khmer.png", alt: "locale", size: "24x24", class: "me-2"

            .font-weight-bold
              .km-font.text-truncate= t('language.km')
        %li
          = link_to url_for(request.query_parameters.merge(locale: 'en')), class: 'switch-language dropdown-item d-flex align-items-center' do
            .dropdown-list-image.me-3
              = image_tag "english.png", alt: "locale", size: "24x24", class: "me-2"
            .font-weight-bold
              .en-font.text-truncate= t('language.en')

app/views/home/faq/_question_1.haml
.accordion-item.mb-2.shadow.border
  = render 'home/faq/question', target: 'One', question: t('question.can_my_project_use_digital_scorecard')

  #collapseOne.accordion-collapse.collapse{"aria-labelledby" => "headingOne", "data-bs-parent" => "#faq"}
    .faq-body.accordion-body
      = t('answer.q1.yes_digital_scorecard_is_free').html_safe

app/views/home/faq/_question_2.haml
.accordion-item.mb-2.shadow.border
  = render 'home/faq/question', target: 'Two', question: t('question.why_should_i_use_digital_scorecard')

  #collapseTwo.accordion-collapse.collapse{"aria-labelledby" => "headingTwo", "data-bs-parent" => "#faq"}
    .faq-body
      = t('answer.q2.digital_scorecard_was_designed').html_safe

      %ul
        %li= t('answer.q2.it_provide_flexibility').html_safe
        %li= t('answer.q2.it_support_khmer_language').html_safe
        %li= t('answer.q2.it_come_with_dashboard').html_safe

      = link_to t('answer.q2.see_here_videos'), "https://www.youtube.com/playlist?list=PLOpKUpKkRrQuWggZRMSIjgAjixiZhXT-j", target: '_blank'

      %span= t('answer.q2.about_digital_scorecard').html_safe

app/views/home/faq/_question_6.haml
.accordion-item.border.mb-2.shadow
  = render 'home/faq/question', target: 'Six', question: t('question.where_can_i_get_support')

  #collapseSix.accordion-collapse.collapse{"aria-labelledby" => "headingSix", "data-bs-parent" => "#faq"}
    .faq-body
      %ul
        %li= t('answer.q6.please_contact_care_and_api').html_safe
        %li= t('answer.q6.please_contact_instedd').html_safe

app/views/shared/_top_header.html.haml
.d-flex.justify-content-center.top-bar
  .content.d-flex.flex-grow-1.align-items-center
    .flex-grow-1
      = link_to root_url do
        = image_tag 'logo.png', class: 'logo'

    .faq-link
      = link_to "FAQ", faq_index_path, class: 'btn text-white'

    / Switch language
    #switch-language.btn-group
      %a#messagesDropdown.nav-link.dropdown-toggle.pe-0{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :type => "button", href: '#'}
        - language = { en: "english.png", km: "khmer.png" }
        = image_tag language[I18n.locale], alt: "locale", size: "24x24"
        %span.ms-1= t("language.#{I18n.locale}")
        %i.fas.fa-angle-down.fa-fw

      %ul.dropdown-menu.dropdown-menu-end
        %li
          = link_to url_for(request.query_parameters.merge(locale: 'km')), class: 'switch-language dropdown-item d-flex align-items-center' do
            .dropdown-list-image.me-3
              = image_tag "khmer.png", alt: "locale", size: "24x24", class: "me-2"

            .font-weight-bold
              .km-font.text-truncate= t('language.km')
        %li
          = link_to url_for(request.query_parameters.merge(locale: 'en')), class: 'switch-language dropdown-item d-flex align-items-center' do
            .dropdown-list-image.me-3
              = image_tag "english.png", alt: "locale", size: "24x24", class: "me-2"
            .font-weight-bold
              .en-font.text-truncate= t('language.en')